/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package analizador;

import analizador.LexicalAnalyser;
import analizador.ModeloDeTabla;
import analizador.Tokens_Lexemas;
import colecano.AnaCanonica;
import colecano.TablaAnaSintac;
import colecano.Tabla_Cano;
import colecano.Tabla_Derivacion_Aceptacion;
import jacv050.ObtenerPS;
import jacv050.PrimerosYSiguientes;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumnos
 */
public class InterfazFinal extends javax.swing.JFrame {
    JFileChooser seleccionar = new JFileChooser("pruebas");
    JFileChooser selec = new JFileChooser("pruebas");
    
    public static File archivo;
    public static File archivo_X;
    public static File archivo_A_S;
    FileInputStream entrada;
    FileOutputStream salida;

    public static String regex = "";
    public static String regex_X = "";
    public static String regex_XX = "";
    public static String regex_X_X = "";
    int bandera = 0;
    int otra_bandera = 0;
    public static int bandera_Accion = 0;
    //-----------------------------------------------------------------------------------
    private static Arbol_Binario arbol_sintactico = new Arbol_Binario();
    public static char epsilon = 'e';
    public static char concat = '.';
    
    private static AFN afn1;
    private static AFD afd2;
    
    public static int contador_automatas_creados=1;
    
    public static boolean imprimir_automatas_en_pantalla=true;
    public static boolean imprimir_debugueo_minimizacion=true;
    
    
    Lexico oAnaLex;
    ModeloDeTabla modelo=null;
    ModeloTablaErrores moderror=null;
    
    //Kevdey agrego esto
    ModeloTablaSimbolos modsim=null;
    
    public static StringBuffer Simbolos = new StringBuffer("");
    public static StringBuffer LiErrores = new StringBuffer("");
    
    public static String aux;

    /**
     * Creates new form InterfazFinal
     */
    public InterfazFinal() {
        initComponents();
        buttonGroupLexico.add(jRadioThompson);
        buttonGroupLexico.add(jRadioAFD);
        buttonGroupLexico.add(jRadioLexico);
        buttonGroupSintactico.add(jRadioPrimSig);
        buttonGroupSintactico.add(jRadioTablaSintac);
        buttonGroupSintactico.add(jRadioColeCano);
        buttonGroupSintactico.add(jRadioAnaSintac);
    }
    
    public String AbriArchivo(File archivo) {
        String documento = "";
        try {
            entrada = new FileInputStream(archivo);
            int ascii;
            while ((ascii = entrada.read()) != -1) {
                char caracter = (char) ascii;
                documento += caracter;
            }
        } catch (Exception e) {

        }
        return documento;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLexico = new javax.swing.ButtonGroup();
        buttonGroupSintactico = new javax.swing.ButtonGroup();
        jPanelBlancoIzquierdo = new javax.swing.JPanel();
        jPanelAzulDerecho = new javax.swing.JPanel();
        jLabelLexico = new javax.swing.JLabel();
        jLabelSemantico1 = new javax.swing.JLabel();
        jRadioThompson = new javax.swing.JRadioButton();
        jRadioAFD = new javax.swing.JRadioButton();
        jRadioLexico = new javax.swing.JRadioButton();
        btnA1 = new javax.swing.JButton();
        jBME2 = new javax.swing.JButton();
        jRadioPrimSig = new javax.swing.JRadioButton();
        jRadioTablaSintac = new javax.swing.JRadioButton();
        jRadioColeCano = new javax.swing.JRadioButton();
        jRadioAnaSintac = new javax.swing.JRadioButton();
        jLabelCod = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxTa1 = new javax.swing.JTextArea();
        jButtonSel1 = new javax.swing.JButton();
        jLabelGram = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxTa3 = new javax.swing.JTextArea();
        jButtonSel2 = new javax.swing.JButton();
        jLabelAccSem = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxTa2 = new javax.swing.JTextArea();
        jButtonSel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBlancoIzquierdo.setBackground(new java.awt.Color(237, 237, 237));

        jPanelAzulDerecho.setBackground(new java.awt.Color(4, 127, 218));

        jLabelLexico.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabelLexico.setForeground(new java.awt.Color(237, 237, 237));
        jLabelLexico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLexico.setText("FASE DE ANÁLISIS SINTÁCTICO-SEMÁNTICO");

        jLabelSemantico1.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabelSemantico1.setForeground(new java.awt.Color(237, 237, 237));
        jLabelSemantico1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSemantico1.setText("FASE DE ANÁLISIS LÉXICO");

        jRadioThompson.setForeground(new java.awt.Color(237, 237, 237));
        jRadioThompson.setText("Algoritmo de Thompson");
        jRadioThompson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioThompsonActionPerformed(evt);
            }
        });

        jRadioAFD.setForeground(new java.awt.Color(237, 237, 237));
        jRadioAFD.setText("AFD");

        jRadioLexico.setForeground(new java.awt.Color(237, 237, 237));
        jRadioLexico.setText("Analizador Léxico");
        jRadioLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLexicoActionPerformed(evt);
            }
        });

        btnA1.setBackground(new java.awt.Color(237, 237, 237));
        btnA1.setText("Mostrar ejecución");
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });

        jBME2.setText("Mostrar ejecución");
        jBME2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBME2ActionPerformed(evt);
            }
        });

        jRadioPrimSig.setForeground(new java.awt.Color(237, 237, 237));
        jRadioPrimSig.setText("Primeros y siguientes");
        jRadioPrimSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPrimSigActionPerformed(evt);
            }
        });

        jRadioTablaSintac.setForeground(new java.awt.Color(237, 237, 237));
        jRadioTablaSintac.setText("Tabla de análisis sintáctico");

        jRadioColeCano.setForeground(new java.awt.Color(237, 237, 237));
        jRadioColeCano.setText("Colección Canónica");

        jRadioAnaSintac.setForeground(new java.awt.Color(237, 237, 237));
        jRadioAnaSintac.setText("Analizador Sintáctico-Semántico");
        jRadioAnaSintac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAnaSintacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAzulDerechoLayout = new javax.swing.GroupLayout(jPanelAzulDerecho);
        jPanelAzulDerecho.setLayout(jPanelAzulDerechoLayout);
        jPanelAzulDerechoLayout.setHorizontalGroup(
            jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulDerechoLayout.createSequentialGroup()
                .addGroup(jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAzulDerechoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioThompson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioAFD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioLexico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelAzulDerechoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(jPanelAzulDerechoLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabelSemantico1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAzulDerechoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAzulDerechoLayout.createSequentialGroup()
                        .addComponent(jRadioPrimSig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(330, 330, 330))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAzulDerechoLayout.createSequentialGroup()
                        .addComponent(btnA1)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAzulDerechoLayout.createSequentialGroup()
                        .addComponent(jBME2)
                        .addGap(205, 205, 205))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAzulDerechoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jRadioTablaSintac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioColeCano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioAnaSintac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanelAzulDerechoLayout.setVerticalGroup(
            jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAzulDerechoLayout.createSequentialGroup()
                .addComponent(jLabelSemantico1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioThompson)
                .addGap(18, 18, 18)
                .addComponent(jRadioAFD)
                .addGap(18, 18, 18)
                .addComponent(jRadioLexico)
                .addGap(47, 47, 47)
                .addComponent(btnA1)
                .addGap(18, 18, 18)
                .addComponent(jLabelLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioPrimSig)
                    .addComponent(jRadioColeCano))
                .addGap(18, 18, 18)
                .addGroup(jPanelAzulDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioTablaSintac)
                    .addComponent(jRadioAnaSintac))
                .addGap(53, 53, 53)
                .addComponent(jBME2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelCod.setFont(new java.awt.Font("BankGothic Lt BT", 1, 24)); // NOI18N
        jLabelCod.setForeground(new java.awt.Color(3, 3, 3));
        jLabelCod.setText("CÓDIGO FUENTE");

        TxTa1.setColumns(20);
        TxTa1.setRows(5);
        jScrollPane1.setViewportView(TxTa1);

        jButtonSel1.setText("Seleccionar Archivo");
        jButtonSel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSel1ActionPerformed(evt);
            }
        });

        jLabelGram.setFont(new java.awt.Font("BankGothic Lt BT", 1, 24)); // NOI18N
        jLabelGram.setForeground(new java.awt.Color(3, 3, 3));
        jLabelGram.setText("ACCIONES SEMÁNTICAS");

        TxTa3.setColumns(20);
        TxTa3.setRows(5);
        jScrollPane2.setViewportView(TxTa3);

        jButtonSel2.setText("Seleccionar Archivo");
        jButtonSel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSel2ActionPerformed(evt);
            }
        });

        jLabelAccSem.setFont(new java.awt.Font("BankGothic Lt BT", 1, 24)); // NOI18N
        jLabelAccSem.setForeground(new java.awt.Color(3, 3, 3));
        jLabelAccSem.setText("GRAMATICA");

        TxTa2.setColumns(20);
        TxTa2.setRows(5);
        jScrollPane3.setViewportView(TxTa2);

        jButtonSel3.setText("Seleccionar Archivo");
        jButtonSel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBlancoIzquierdoLayout = new javax.swing.GroupLayout(jPanelBlancoIzquierdo);
        jPanelBlancoIzquierdo.setLayout(jPanelBlancoIzquierdoLayout);
        jPanelBlancoIzquierdoLayout.setHorizontalGroup(
            jPanelBlancoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBlancoIzquierdoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelBlancoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBlancoIzquierdoLayout.createSequentialGroup()
                        .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelBlancoIzquierdoLayout.createSequentialGroup()
                        .addComponent(jLabelGram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelBlancoIzquierdoLayout.createSequentialGroup()
                        .addComponent(jLabelAccSem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addComponent(jPanelAzulDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBlancoIzquierdoLayout.setVerticalGroup(
            jPanelBlancoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAzulDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBlancoIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBlancoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBlancoIzquierdoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonSel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanelBlancoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGram)
                    .addComponent(jButtonSel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanelBlancoIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelAccSem)
                    .addComponent(jButtonSel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlancoIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBlancoIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
        int index = 0;
        if(jRadioThompson.isSelected())
        {
            index=0;
        }
        if(jRadioAFD.isSelected())
        {
            index=1;
        }
        if(jRadioLexico.isSelected())
        {
            index = 2;
        }
        String Documento = InterfazFinal.regex_X;
        Nodo.contador_nodos=1;
        
        if(index != 2)
        {
            boolean error=false;
            try
            {
                if(!error)
                    arbol_sintactico.Generar_arbol(Documento);
            }
            catch(Exception exp)
            {
                System.out.println("Error al generar el arbol");
                error=true;
            }
          
            if(index == 0 || index == 1)
            {   
                if(!error)
                {
                    try
                    {
                        afn1 = new AFN(arbol_sintactico);
                    }
                    catch(Exception exp)
                    {
                        System.out.println("Error al generar en AFN con Thompson");
                        afn1=null;
                        error=true;
                    }
                }
                if(index == 0)
                {
                    TablaSol sol = new TablaSol();
                    sol.setVisible(true);
                }
                if(index == 1)
                {
                    if(!error){
                        try
                        {
                            //CONVERTIR EL AFN A UN AFD CON SUBCONJUNTOS
                            afd2 = new AFD(afn1);

                            contador_automatas_creados++;
                        }catch(Exception exp){
                            System.out.println("Error al generar el AFD con subconjuntos");
                            afd2=null;
                            error=true;
                        }
                    }
                    
                    AFDSub sub = new AFDSub();
                    sub.setVisible(true);
                }
            }
        }
        
        if(index == 2 && otra_bandera == 0)
        {
            try {
                LexicalAnalyser user = new LexicalAnalyser(regex_XX);                
            } catch (IOException ex) {
                Logger.getLogger(InterfazFinal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Tokens_Lexemas ssa = new Tokens_Lexemas();
            ssa.setVisible(true);
            
            moderror = new ModeloTablaErrores();
            ErroresList ss= new ErroresList();
            ss.setVisible(true);
            
            //Kevdey agrego esto
            TablaSimbolos ts= new TablaSimbolos();
            ts.setVisible(true);        
            
            //Tabla de Errores                        
        }
        
    }//GEN-LAST:event_btnA1ActionPerformed

    private void jRadioThompsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioThompsonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioThompsonActionPerformed

    private void jRadioLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLexicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioLexicoActionPerformed

    private void jBME2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBME2ActionPerformed
        // TODO add your handling code here:
        int Opcion = 0;
        if(jRadioPrimSig.isSelected())
        {
            Opcion = 0;
        }
        if(jRadioColeCano.isSelected())
        {
            Opcion = 1;
        }
        if(jRadioTablaSintac.isSelected())
        {
            Opcion = 2;
        }
        if(jRadioAnaSintac.isSelected())
        {
            Opcion = 3;
        }
        //bandera_Accion = Box02.getSelectedIndex();
        
        if(Opcion != 0 && bandera == 0)
        {
            ObtenerPS pred = new ObtenerPS(InterfazFinal.archivo);
            AnaCanonica aux = new AnaCanonica(regex,regex_X_X,bandera_Accion);                        
            bandera = 1;
        }
        
        if(Opcion == 0)
        {
            ObtenerPS predi = new ObtenerPS(InterfazFinal.archivo);
            PrimerosYSiguientes sol = new PrimerosYSiguientes();
            sol.setVisible(true);
        }
        
        if(Opcion == 1)
        {
            Tabla_Cano sol = new Tabla_Cano();
            sol.setVisible(true);            
        }

        if(Opcion == 2)
        {
            TablaAnaSintac tac = new TablaAnaSintac();
            tac.setVisible(true);
        }
        
        if(Opcion == 3)
        {
            Tabla_Derivacion_Aceptacion sac = new Tabla_Derivacion_Aceptacion();
            sac.setVisible(true);
        }
    }//GEN-LAST:event_jBME2ActionPerformed

    private void jRadioPrimSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPrimSigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPrimSigActionPerformed

    private void jButtonSel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSel2ActionPerformed
        // TODO add your handling code here:
        if (selec.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo_A_S = selec.getSelectedFile();
            if (archivo_A_S.canRead()) {
                if (archivo_A_S.getName().endsWith("txt")) {
                    String documento = AbriArchivo(archivo_A_S);
                    TxTa3.setText(documento);
                    InterfazFinal.regex_X_X = InterfazFinal.archivo_A_S.toString();
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }
        }
    }//GEN-LAST:event_jButtonSel2ActionPerformed

    private void jButtonSel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSel3ActionPerformed
        // TODO add your handling code here:
        if (seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("txt")) {
                    String documento = AbriArchivo(archivo);
                    TxTa2.setText(documento);
                    InterfazFinal.regex = InterfazFinal.archivo.toString();
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }
        }
    }//GEN-LAST:event_jButtonSel3ActionPerformed

    private void jRadioAnaSintacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAnaSintacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioAnaSintacActionPerformed

    private void jButtonSel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSel1ActionPerformed
        // TODO add your handling code here:
        if (selec.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo_X = selec.getSelectedFile();
            if (archivo_X.canRead()) {
                if (archivo_X.getName().endsWith("txt")) {
                    String documento = AbriArchivo(archivo_X);
                    TxTa1.setText(documento);
                    InterfazFinal.regex_X = documento;
                    InterfazFinal.regex_XX = archivo_X.toString();
                } else {
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }
        }
    }//GEN-LAST:event_jButtonSel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxTa1;
    private javax.swing.JTextArea TxTa2;
    private javax.swing.JTextArea TxTa3;
    private javax.swing.JButton btnA1;
    private javax.swing.ButtonGroup buttonGroupLexico;
    private javax.swing.ButtonGroup buttonGroupSintactico;
    private javax.swing.JButton jBME2;
    private javax.swing.JButton jButtonSel1;
    private javax.swing.JButton jButtonSel2;
    private javax.swing.JButton jButtonSel3;
    private javax.swing.JLabel jLabelAccSem;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelGram;
    private javax.swing.JLabel jLabelLexico;
    private javax.swing.JLabel jLabelSemantico1;
    private javax.swing.JPanel jPanelAzulDerecho;
    private javax.swing.JPanel jPanelBlancoIzquierdo;
    private javax.swing.JRadioButton jRadioAFD;
    private javax.swing.JRadioButton jRadioAnaSintac;
    private javax.swing.JRadioButton jRadioColeCano;
    private javax.swing.JRadioButton jRadioLexico;
    private javax.swing.JRadioButton jRadioPrimSig;
    private javax.swing.JRadioButton jRadioTablaSintac;
    private javax.swing.JRadioButton jRadioThompson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
